### ISSUE TITLE
Import and Getopt::Long

### ISSUE THREAD

**Issue by pdl** [PerlDancer/Dancer#1096]
Similar to #637, I've come across some rather frustrating behaviour when writing scripts for Dancer.

```perl
#!/usr/bin/perl
use strict;
use warnings;

use Dancer ':script';
use Foo;
use Getopt::Long qw(GetOptions);
my ($dry_run);

GetOptions(
  'dry-run|d!'    => \$dry_run,
);

print "ok $dry_run" if $dry_run;
```

```perl
package Foo;
use Dancer 'from_json';
1;
```

In this case, even though I am using `:script` in my script, because I am loading a package which does not use `:script` or `:syntax` but instead loads symbols from Dancer by name, Dancer jumps in and processes the options before I get to them, and dies, complaining that dry-run is not a recognised option.

The script works fine if it does not use Foo or Foo does not use Dancer.

What I would expect Dancer to do is realise it has been called with `:script` and never process command-line arguments, even if it is later imported with some argument other than `:script`.

My preference would be that only `use Dancer;` without arguments (and not `use Dancer ();`) should try to do clever things like grabbing command-line arguments and setting `appdir`. Ideally, it should be possible to do the clever stuff on demand (without necessarily importing symbols) with something like `use Dancer (); Dancer::initialise;` or `use Dancer qw(:app);`. I have a suspicion this might break things for some people.

The only way round this I can see for me is always using `use Dancer qw(:syntax);` and nothing else in my app packages whenever I want to use anything from Dancer. That's a bit of a pain, especially if I want to use other modules with conflicting symbols from something else.

**Comment by yanick** [comment]
#1096 has been merged in, and should take care of the issue.
