### ISSUE TITLE
t/01_config/06_config_api.t fails with YAML 1.15

### ISSUE THREAD

**Issue by eserte** [PerlDancer/Dancer#1107]
On my smokers (freebsd, linux, various perls) there's a 100% chance for `t/01_config/06_config_api.t` to fail if YAML 1.15 is installed. This does not happen for earlier YAML versions. Test fail looks like this:

```
#   Failed test at t/01_config/06_config_api.t line 33.
#                   'Can't use string ("foo\n") as a HASH ref while "strict refs" in use at /tmpfs/.cpan-build/Dancer-1.3134-v8X88T/blib/lib/Dancer/Config.pm line 238.
# '
#     doesn't match '(?^:Unable to parse the configuration file)'
# Looks like you failed 1 test of 2.
t/01_config/06_config_api.t ......................... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests 
```

**Comment by eserte** [comment]
It seems that the failure happens because YAML.pm is now more liberal --- before 1.15 a final newline was required, but with 1.15 it is not anymore required.

**Comment by ingydotnet** [comment]
I made YAML.pm match the behavior of the other Perl YAML loaders.

**Comment by ambs** [comment]
Consistency is good.

**Comment by ingydotnet** [comment]
Well, and also matching the actual rules of the YAML spec is good. At the recent QA hackathon in Berlin, I (re)started the efforts to bring YAML implementations all work the same and correctly.
