### ISSUE TITLE
t/01_config/06_config_api.t fails with YAML 1.15

### ISSUE THREAD

**Issue by andk** [PerlDancer/Dancer#1110]
As per subject. Sample fail report:

http://www.cpantesters.org/cpan/report/ee97a5b6-e781-11e4-859c-fd8de0bfc7aa

HTH&&Thanks,
(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by yanick** [comment]
The test should be okay with Dancer 1.3135

Thanks for the report!
