### ISSUE TITLE
Scrub session modules for bad files

### ISSUE THREAD

**Issue by yanick** [PerlDancer/Dancer#1118]
- [ ]  Dancer::Session::JSON
 - [ ] Dancer::Session::Storable

**Comment by bigpresh** [comment]
@yanick, is this still an issue? As it's been left for so long, and is lacking any details on what you mean by "bad files", I'm going to close it - but feel free to re-open with more details if it's something that still needs handling.

**Comment by yanick** [comment]
If I remember correctly this has to do with #1117, where somebody can pass an id of, say, '../../../etc/password' and have the session module try to load that file.

As far as I'm concerned, it's still an issue. Or, at least, the investigation is still pending.

**Comment by bigpresh** [comment]
Fuck-a-doodle-do, that looks like a hideous problem that should have been fixed long ago!

**Comment by bigpresh** [comment]
Hmm. The `$id` passed to .e.g `Dancer::Sesssion::YAML->fetch()` is usually passed to it by `Dancer::Session->get_current_session()`, which get it via `read_session_id` as follows:

```perl
my $sid     = engine->read_session_id;
my $session = undef;
my $class   = ref(engine);
$session = $class->retrieve($sid) if $sid;
```

It seems like `Dancer::Session::Abstract->read_session_id` would be a logical place for a "this doesn't look like a cromulent session ID, go away" check, which would automatically protect all session engines, rather than each session engine's `retrieve` method having to handle it.

**Comment by cromedome** [comment]
:+1:

**Comment by bigpresh** [comment]
I've had to revert the change for this, because it breaks Dancer::Session::Cookie, which uses `read_session_id` to read the actual session contents from the session cookie.  So, each session engine which uses file-based storage needs to make sure it handles the session ID given to it securely.

**Comment by racke** [comment]
On 02/16/2016 11:29 PM, David Precious wrote:

> I've had to revert the change for this, because it breaks Dancer::Session::Cookie, which uses |read_session_id| to read the actual session contents from the session cookie. 
> So, each session engine which uses file-based storage needs to make sure it handles the session ID given to it securely.

It is more secure if we add a flag to the base session module which allows Dancer::Session::Cookie to skip
the validation.

Regards
    Racke

## 

Perl and Dancer Development

Visit our Perl::Dancer conference 2015.
More information on https://www.perl.dance.
