### ISSUE TITLE
Default config drops log files in working directory

### ISSUE THREAD

**Issue by yanick** [PerlDancer/Dancer#1121]
From the dancer-user mailing list

Hi,

Delurking, because the latest version of Dancer is causing our unit tests at $WORK to start creating empty log files inside the current working directory. This is easily-reproducible: e.g.

> sam@chimera64:tmp$ cat spamlogfile.pl 
> #!/usr/bin/env perl
>
> use Dancer qw(halt);
> sam@chimera64:tmp$ rm -fr logs; perl spamlogfile.pl
> sam@chimera64:tmp$ ls -lah logs/
> total 40K
> drwxr-xr-x  2 sam  sam  4.0K Jun 22 17:01 .
> drwxrwxrwt 10 root root  36K Jun 22 17:01 ..
> -rw-r--r--  1 sam  sam     0 Jun 22 17:01 development.log

A workaround is to say use Dancer qw(:syntax), but there are two problems with that:

(1) this is a change in behaviour that wasn’t documented as such, and it requires all auxiliary non-server Dancer code to be changed; and

(2) passing :syntax imports all sorts of Dancer symbols that can potentially clash with a parent class.

I’ve spent the afternoon debugging point 2. Our end-to-end tests run under Test::Dancer, and we have a separate class that tests individual method calls as if they were Dancer requests (including setting the status code in case of errors). It previously said use Dancer () and explicitly called Dancer::status - and under Dancer 1.3138, running unit tests using this class would generate spurious empty log files.

I patched that to say use Dancer qw(:syntax) - and now the code fails because the parent class implements methods true, false and redirect, which the method call class never gets to call because it’s had Dancer’s symbols stuck in its own package instead. So this now needs to say use Dancer qw(:syntax !true !false !redirect), and in practice I needed to write an automated test script that checked that all of a parent class’s methods were explicitly not imported from Dancer, because if I change anything upstream I need to change the import statement in the child classes.

The problem appears to have been introduced in https://github.com/PerlDancer/Dancer/commit/e9e4e087528c2734dd6e9c922105eac3cd2e53e7

The actual problem is further down in Dancer::Config - line 227 in 1.3138 - where the settings are read. $SETTINGS at this point contains default values, and part of setting confdir involves creating a logs subdirectory. Previously the code wouldn’t get this far.

Presumably a workaround would be to not create a log directory immediately, but then if you were running a real Dancer server you’d want to know as soon as possible that your log directory wasn’t writable, so that’s not going to be acceptable to many people.

Alternatively, any code that says e.g. use Dancer qw(halt status) should be seen as clearly not wanting to actually start a Dancer server or anything like that. That sounds like a scary change to make, though.

Or you could defer parsing of the Dancer config until something actually happens. That’s also vague and terrifying.

Or just revert that particular commit / PR. I don’t fully understand why it does what it does, though. If there’s a way of cleanly telling apart (1) a hash of settings that was explicitly passed to Dancer from (2) the default settings that, chances are, you didn’t intend to use, that would  be the best solution to my mind.

Sam

**Comment by fgabolde** [comment]
Oops, that would be my bad.

I guess the fix to return to the previous behavior re. the SETTINGS hooks is not to run that block if there is no conffile and no hashref was provided, or you could revert my patch and I'll just have to find another way to configure my app.

**Comment by yanick** [comment]
Yeah, I think the commit mentioned above takes care of that. But there's a discussion going on between the crew about feature freeze, so for the moment I'm just going to revert the original patch.

**Comment by fgabolde** [comment]
@yanick Sorry about the mess.

I knew about the feature freeze, but we needed this patch for $work and we can't switch to Dancer2 even though this is a new, smallish app because of the performance hit (we get something like 40% more performance with D1).

**Comment by yanick** [comment]
@fgabolde  No problem. No progress is made without little squeals of pain. ^.^

@xsawyerx as you you'll be the gatekeeper before long, you may want to read this thread and see what we want to do there.

**Comment by xsawyerx** [comment]
If this is a matter of breakage, it has to be reverted. We can reattempt that patch, but as I've said in the original one, it introduces even more state which can cause (and did in this case) more problems.

For now, the sane solution, IMHO, would be to revert the patch until it can be applied safely - something I'm not sure can be done, unless we go completely overboard with the implementation.

@fgabolde That's an incredible difference. Can you please provide me with the benchmarks? There is no reason D1 should be faster, let alone *this much* faster. Latest Github version, by the way, introduces about 13-14% speed improvement in request instantiation.

**Comment by bigpresh** [comment]
I think I'd vote to revert too as it's causing issues.

Incidentally, I saw a user on IRC who was finding that the app was launching on port 3000 even though his config said otherwise - is this also related?

```
18:41 < art> Hi! Why I can't set custom port in my app? Here my config.yml http://pastebin.com/8MbXFTPA
18:41 <@sophie> [ appname: 'WebApp' layout: 'main' charset: 'UTF-8' template: 'template_toolkit - Pastebin.com ] 
18:44 < b10m> art: how do you serve that? Plackup?
18:46 < art> http://pastebin.com/D65rU4cX
18:46 <@sophie> [ #app.pl #!/usr/bin/env perl use local::lib; use FindBin; use lib "$FindBin - Pastebin.com ] 
18:47 < art> b10m: hope that will help
18:50 < b10m> and it keeps launching a server at port 3000 ?
18:50 < art> Yes!
18:51 < art> It reads "layout:" from config, but ignores "port:"
18:51 < b10m> hmm, odd indeed. This used to work in D1 for sure
18:51 < b10m> brb ...
18:59 < b10m> set port => 3001; in your WebApp.pm should do the trick for now
19:01 < art> I know this method, but I want to keep all settings in one place :(
19:02 < art> This is not very important. Thanks you for attention.
19:04 < b10m> looks like it's a bug though
19:04 < b10m> another option is to set the DANCER_PORT env variable btw
19:04 < b10m> but still, this _should_ work ;)
19:06 < art> b10m: Okay, thanks again. Goodbye!
19:07 -!- art [5f1d74a9@ircip3.mibbit.com] has quit [Quit: http://www.mibbit.com ajax IRC Client]
19:12 < b10m> ah, the settings are read -after- we launch the server :-/
```

**Comment by xsawyerx** [comment]
So it would appear it now hit my company too. :)

**Comment by fgabolde** [comment]
@bigpresh I don't *think* this is related.  The `config.yml` stuff is untouched, I made sure of that at least...  I sure didn't change the timing of the first call to `Dancer::Config->load`.  Still, better safe than sorry, reversion sounds like the best plan for you guys.

@xsawyerx If current D2 has caught up with D1 performance-wise then I'll be happy to port our app to D2.  Likewise if my bench is flawed!  My benchmark is basically running `GET  '/?foo=bar&baz=quux'` over and over against three Plack::Test harnesses, one with D1, one with D2, one with a pure Plack app with very rudimentary "routing".  I ran it against latest D1 and D2 0.160000, and again with D2 0.160003 (current latest).

                 Rate    dancer2     dancer pure_plack
    dancer2     972/s         --       -30%       -81%
    dancer     1389/s        43%         --       -73%
    pure_plack 5093/s       424%       267%         --

I believe this matches what I want to test fairly well.  Our app has barely 3 routes with no route params and never returns HTML, only redirects or `400 Bad params`.  It has side-effects like writing to a message queue but those are not framework-specific.  It does log warnings and errors (to STDOUT currently, syslog later) but I hope this isn't too much of a factor in the framework's performance :/

I couldn't test it against D2 master, it doesn't install cleanly on my setup:

    $ dzil install
    [DZ] building distribution under .build/0QTOSHXTiF for installation
    [DZ] beginning to build Dancer2
    [DZ] dist's main_module is lib/Dancer2.pm
    [@Filter/ExtraTests] rewriting release test xt/release/distmeta.t
    [@Filter/ExtraTests] rewriting author test xt/author/no-tabs.t
    [@Filter/ExtraTests] rewriting release test xt/release/pod-syntax.t
    [DZ] extracting distribution abstract from lib/Dancer2.pm
    [@Filter/MetaProvides::Package] No namespaces detected in file lib/Dancer2/Manual/Deployment.pod
    Strings with code points over 0xFF may not be mapped into in-memory file handles
    error opening string for reading: Invalid argument at /home/fgabolde/perl5/perlbrew/perls/dataranger/lib/site_perl/5.18.2/Mixin/Linewise/Readers.pm line 134.

This is all vanilla Perl 5.18.2 by the way, installed straight from perlbrew.  URL::Encode::XS, CGI::Deurl::XS and HTTP::Parser::XS are all at their latest CPAN version.

I'll create a repo with my bench code if you want to check it.

**Comment by xsawyerx** [comment]
@fgabolde This is really strange. I'd like to first fix the install error. Any way we can get access to an instance with such an install error?

The benchmarks that I made provided 25% at best, not 43%. I'm going to look over yours. Thank you for posting them!

**Comment by fgabolde** [comment]
@xsawyerx This is my dev machine at Weborama; I mostly trust you but I don't think my sysadmin knows you :)

I can try asking some other devs if they can replicate the issue, and I can certainly rebuild a pristine Perl 5.18.2 and dzil build from scratch.

**Comment by xsawyerx** [comment]
@fgabolde that would be very helpful! Thank you. :)

**Comment by fgabolde** [comment]
@xsawyerx

From a brand-new Perl 5.18.2, on the master branch (currently 70f3d86):

    $ cpanm Dist::Zilla
    # wait a long time, then wait some more
    $ dzil authordeps --missing | cpanm
    # wait, but less
    $ dzil listdeps --missing | cpanm
    # wait...
    $ dzil build
    # aaaaand, no crash :/

Just for gits and shiggles I installed the newest Dist::Zilla, but no changes on the other Perl:

    $ dzil build
    [DZ] beginning to build Dancer2
    [@Filter/ExtraTests] rewriting release test xt/release/distmeta.t
    [@Filter/ExtraTests] rewriting author test xt/author/no-tabs.t
    [@Filter/ExtraTests] rewriting release test xt/release/pod-syntax.t
    [@Filter/MetaProvides::Package] No namespaces detected in file lib/Dancer2/Manual/Deployment.pod
    Strings with code points over 0xFF may not be mapped into in-memory file handles
    error opening string for reading: Invalid argument at /home/fgabolde/perl5/perlbrew/perls/dataranger/lib/site_perl/5.18.2/Mixin/Linewise/Readers.pm line 134.

I don't really know what's the difference between both installs of Perl.  I might tree-diff the $VERSIONs in both `site_lib`s if I have time tomorrow.

At least now I can run my bench against master!

**Comment by xsawyerx** [comment]
@fgabolde We have just merged an optimization branch that shows (with included benchmark utility) that D2 surpasses D1.

We still have more room to optimize but I do believe this gives you a good reason to consider switching to D2. :)

**Comment by fgabolde** [comment]
@xsawyerx On my benchmark, the current master of D2 just caught up with D1 (within 5%). I can't see what we're doing very differently though...

Still, even just catching up would be enough to justify a switch. I still need to be able to load configuration data from sources other than files; can we do this in D2, is it planned, or not at all?
