### ISSUE TITLE
"Use of uninitialized value $_ in split at ... Route.pm" when using optional megasplat

### ISSUE THREAD

**Issue by Relequestual** [PerlDancer/Dancer#1144]
When creating a route that uses an optional megasplat, and then accessing the route without the optional parts, warning thrown `Use of uninitialized value $_ in split ..... Route.pm line 96.`

Dancer version 1.3202

I'd like to be able to create a test which shows this, however I am unable to install the Safe module on osx, which is an auther dependency.

Example route:
`/API/users/?**?`

**Comment by bigpresh** [comment]
Sorry for the massive delay responding to this.  I'll try to rock up a test to reproduce it, and get a fix in place.

**Comment by Relequestual** [comment]
No worries at all. Ended up working round it by not actually needing to use megasplat.
Thanks again for your continued work on D1 maintenance =]

**Comment by bigpresh** [comment]
Yeah, able to reproduce against current master, simple test app that defines a route `/foo/?**?` - every time I hit it as just `/foo` I get a warning:

`Use of uninitialized value $values[0] in split at .../Dancer/lib/Dancer/Route.pm line 137.`

**Comment by Relequestual** [comment]
Nice. I wonder if the same bug exists in D2.
If I had time this week to set up a VM and check it out, I would do!

**Comment by bigpresh** [comment]
This bug does indeed exist in D2.  I've PR'd a fix for both :)

Thanks again for the report!

**Comment by Relequestual** [comment]
Skills! Especially given the time of day! Falling asleep myself!
