### ISSUE TITLE
Dancer install fails on windows 7 with strawberry Perl 5.22.1

### ISSUE THREAD

**Issue by itcharlie** [PerlDancer/Dancer#1145]
example short output after running cpanm Dancer via cmd

+++++++++++++++++++++++++
Building and testing Hash-MultiValue-0.16 ... OK
Successfully installed Hash-MultiValue-0.16
--> Working on Devel::StackTrace::AsHTML
Fetching http://www.cpan.org/authors/id/M/MI/MIYAGAWA/Devel-StackTrace-AsHTML-0.
14.tar.gz ... OK
Configuring Devel-StackTrace-AsHTML-0.14 ... OK
Building and testing Devel-StackTrace-AsHTML-0.14 ... OK
Successfully installed Devel-StackTrace-AsHTML-0.14
! Installing the dependencies failed: Module 'Test::TCP' is not installed
! Bailing out the installation for Plack-1.0039.
--> Working on Devel::Hide
Fetching http://www.cpan.org/authors/id/F/FE/FERREIRA/Devel-Hide-0.0009.tar.gz .
.. OK
Configuring Devel-Hide-0.0009 ... OK
Building and testing Devel-Hide-0.0009 ... OK
Successfully installed Devel-Hide-0.0009
! Installing the dependencies failed: Module 'Plack::Builder' is not installed
! Bailing out the installation for Dancer-1.3202.
cannot remove directory for C:\Users\CGONZA~1\.cpanm\work\1451882555.900\IO-Sock
et-SSL-2.022\blib: Directory not empty at C:\Strawberry\perl\bin\cpanm.bat line
45.
cannot remove directory for C:\Users\CGONZA~1\.cpanm\work\1451882555.900\IO-Sock
et-SSL-2.022: Directory not empty at C:\Strawberry\perl\bin\cpanm.bat line 45.
cannot remove directory for C:\Users\CGONZA~1\.cpanm\work\1451882555.900\libwww-
perl-6.15\t\live: Directory not empty at C:\Strawberry\perl\bin\cpanm.bat line 4
5.
cannot remove directory for C:\Users\CGONZA~1\.cpanm\work\1451882555.900\libwww-
perl-6.15\t: Directory not empty at C:\Strawberry\perl\bin\cpanm.bat line 45.
cannot remove directory for C:\Users\CGONZA~1\.cpanm\work\1451882555.900\libwww-
perl-6.15: Directory not empty at C:\Strawberry\perl\bin\cpanm.bat line 45.
cannot remove directory for C:\Users\CGONZA~1\.cpanm\work\1451882555.900\List-Mo
reUtils-0.413\t\lib: Directory not empty at C:\Strawberry\perl\bin\cpanm.bat lin
e 45.
cannot remove directory for C:\Users\CGONZA~1\.cpanm\work\1451882555.900\List-Mo
reUtils-0.413\t: Directory not empty at C:\Strawberry\perl\bin\cpanm.bat line 45
.
cannot remove directory for C:\Users\CGONZA~1\.cpanm\work\1451882555.900\List-Mo
reUtils-0.413: Directory not empty at C:\Strawberry\perl\bin\cpanm.bat line 45.
cannot remove directory for C:\Users\CGONZA~1/.cpanm/work/1451882555.900: Direct
ory not empty at C:\Strawberry\perl\bin\cpanm.bat line 45.
16 distributions installed
PS C:\Users\cgonzalez>

PS C:\Users\cgonzalez> perl -v

This is perl 5, version 22, subversion 1 (v5.22.1) built for MSWin32-x64-multi-t
hread

Copyright 1987-2015, Larry Wall

**Comment by itcharlie** [comment]
The build from Test::TCP is showing some failing tests ( I believe this is the reason why the installation is failing ):

cpanm (App::cpanminus) 1.7039 on perl 5.022001 built for MSWin32-x64-multi-thread
Work directory is C:\Users\CGONZA~1/.cpanm/work/1452683723.3220
You have make C:\Strawberry\c\bin\dmake.exe
You have LWP 6.15
Falling back to Archive::Tar 2.04
Searching Test::TCP () on cpanmetadb ...
--> Working on Test::TCP
Fetching http://www.cpan.org/authors/id/T/TO/TOKUHIROM/Test-TCP-2.14.tar.gz
-> OK
Unpacking Test-TCP-2.14.tar.gz
Entering Test-TCP-2.14
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.10)
Configuring Test-TCP-2.14
Running Makefile.PL
Checking if your kit is complete...
Looks good
Generating a dmake-style Makefile
Writing Makefile for Test::TCP
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Test::SharedFork 0.29 ... Yes (0.35)
Checking if you have Socket 0 ... Yes (2.021)
Checking if you have Time::HiRes 0 ... Yes (1.9728)
Checking if you have Test::More 0.98 ... Yes (1.001014)
Checking if you have File::Temp 0 ... Yes (0.2304)
Checking if you have IO::Socket::INET 0 ... Yes (1.35)
Checking if you have IO::Socket::IP 0 ... Yes (0.37)
Building and testing Test-TCP-2.14
cp lib/Net/EmptyPort.pm blib\lib\Net\EmptyPort.pm
cp lib/Test/TCP/CheckPort.pm blib\lib\Test\TCP\CheckPort.pm
cp lib/Test/TCP.pm blib\lib\Test\TCP.pm
"C:\Strawberry\perl\bin\perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib\lib', 'blib\arch')" t/*.t
# Test::More: 1.001014
t/00_compile.t ................. ok
cannot open port: ::1:51277 at C:\Users\CGONZA~1\.cpanm\work\1452683723.3220\Test-TCP-2.14\blib\lib/Test/TCP.pm line 54.
    # Child (v6) exited without calling finalize()

#   Failed test 'v6'
#   at C:/Strawberry/perl/lib/Test/Builder.pm line 279.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 2.
t/01_simple.t .................. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/2 subtests 
t/02_abrt.t .................... skipped: win32 doesn't support embedded function named dump()
t/03_return_when_sigterm.t ..... ok
t/04_die.t ..................... ok
t/05_sigint.t .................. skipped: this test requires SIGUSR1
t/06_nest.t .................... ok
t/07_optional.t ................ ok
t/08_exit.t .................... ok
t/09_fork.t .................... ok
t/10_oo.t ...................... ok
    
    #   Failed test 'port is open'
    #   at t/11_net_empty_port.t line 22.
    # Looks like you failed 1 test of 4.

#   Failed test 'v6'
#   at t/11_net_empty_port.t line 37.
# Looks like you failed 1 test of 4.
t/11_net_empty_port.t .......... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/4 subtests 
t/12_pass_wait_port_options.t .. ok
t/13_undef_port.t .............. ok

Test Summary Report
-------------------
t/01_simple.t                (Wstat: 65280 Tests: 2 Failed: 1)
  Failed test:  2
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/11_net_empty_port.t        (Wstat: 256 Tests: 4 Failed: 1)
  Failed test:  4
  Non-zero exit status: 1
Files=14, Tests=117, 88 wallclock secs ( 0.11 usr +  0.00 sys =  0.11 CPU)
Result: FAIL
Failed 2/14 test programs. 2/117 subtests failed.
dmake.exe:  Error code 255, while making 'test_dynamic'
-> FAIL Installing Test::TCP failed. See C:\Users\CGONZA~1\.cpanm\work\1452683723.3220\build.log for details. Retry with --force to force install it.
Expiring 1 work directories.

**Comment by bigpresh** [comment]
Sorry for the massive delay in responding to this.  So, it looks likely that Test::TCP is failing, rather than Dancer itself?  Do you get test failures for Test::TCP if you try to install it directly?

**Comment by itcharlie** [comment]
I force installed the module and it works now. If I see this issue again I will create an issue ticket for Test::TCP.  Marking issue closed.

**Comment by bigpresh** [comment]
Thanks @itcharlie!
