### ISSUE TITLE
[Dancer-1.3203-TRIAL]Warning: the following files are missing in your kit

### ISSUE THREAD

**Issue by twata1** [PerlDancer/Dancer#1182]
Hi, Running Strawberry Perl 5.26.1 32 bit, I noticed the following message. 

```
C:\home\bath1>cpan BIGPRESH/Dancer-1.3203-TRIAL.tar.gz
```
(snip)
```
Configuring B/BI/BIGPRESH/Dancer-1.3203-TRIAL.tar.gz with Makefile.PL
CPAN: CPAN::Reporter loaded ok (v1.2018)
Checking if your kit is complete...
Warning: the following files are missing in your kit:
        CONTRIBUTORS
        cpanfile
        doap.xml
        INSTALL
        README
        README.mkdn
        SIGNATURE
Please inform the author.
```
(snip)

Thank you,

--
twata

**Comment by bigpresh** [comment]
Many thanks!

I'm releasing a new trial build shortly which should have those issues
fixed.

I'm still figuring out Dist::Zilla, and switched the project from
Dist::Zilla::PluginBundle::YANICK to ::Dancer, but needed to make some
further updates to make it work.
