### ISSUE TITLE
[Dancer-1.3203-TRIAL] 'invalid yaml file' test may fail

### ISSUE THREAD

**Issue by eserte** [PerlDancer/Dancer#1184]
On some of my smoker systems the following test fails:
```
#   Failed test 'invalid yaml file'
#   at t/01_config/06_config_api.t line 37.
#                   ''
#     doesn't match '(?^:Unable to parse the configuration file)'
# Looks like you failed 1 test of 2.
t/01_config/06_config_api.t ......................... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests 
```

Statistical analysis does not find any possible reasons for this problem. Especially it does not seem to depend on the YAML.pm version.

**Comment by bigpresh** [comment]
Hmm, odd.  As far as I can think, none of my recent changes should have any effect on YAML parsing at all.  I'll have a dig.

Thanks for the report!

**Comment by eserte** [comment]
This seems to happen if YAML is installed and YAML::XS is not.

**Comment by bigpresh** [comment]
Ah, bingo, thanks.

My initial suspicion was that the difference was going to be whether YAML::XS was used or not, but Dancer::Serialiser::YAML doesn't attempt to load it unless told to.

But, in the test that fails:

```perl
my $module = Dancer::ModuleLoader->load('YAML::XS') ? 'YAML::XS' : 'YAML';

eval {
    Dancer::Config::load_settings_from_yaml('foo', $module);
};
```

So, yes, you're absolutely right:

```
[davidp@supernova:~/dev/github/Dancer]$ perl  t/01_config/06_config_api.t
1..2
ok 1 - non-existent yaml file
ok 2 - invalid yaml file
[davidp@supernova:~/dev/github/Dancer]$ perl -MTest::Without::Module=YAML::XS t/01_config/06_config_api.t
1..2
ok 1 - non-existent yaml file
not ok 2 - invalid yaml file
#   Failed test 'invalid yaml file'
#   at t/01_config/06_config_api.t line 37.
#                   ''
#     doesn't match '(?^:Unable to parse the configuration file)'
# Looks like you failed 1 test of 2.
```

I don't like that that test's behaviour is essentially random depending on the system it's on. If anything, it ought to test both modules to check both behave right, skipping YAML::XS if it's not available, so at least it'd be checking that they both behave identically.

Thanks for the pointer, appreciate it!

**Comment by bigpresh** [comment]
PR #1189 should fix this.

**Comment by bigpresh** [comment]
A new trial version Dancer-1.3205-TRIAL has been pushed to GitHub with a fix for this, so I'll close this issue.  Thanks for the report, and thanks again for the pointer in the right direction :)

https://metacpan.org/release/BIGPRESH/Dancer-1.3205-TRIAL
