### ISSUE TITLE
proxy related failure with 1.3500 in t/02_request/20_body.t

### ISSUE THREAD

**Issue by gregoa** [PerlDancer/Dancer#1204]
Adding HTTP::Tiny::NoProxy and using it for the tests is a nice new fetaure and works well, except that `t/02_request/20_body.t` still fails when http_proxy is set. I haven't looked too closely but I assume this is because the test uses 127.0.0.11 but HTTP::Tiny::NoProxy only sets no_proxy for 127.0.0.1.

**Comment by bigpresh** [comment]
Dancer-1.3513 is on its way to CPAN now with a fix that should solve this (as you say, 127.0.0.1 was passed to HTTP::Tiny's `no_proxy`, but `127.0.0.11` wasn't)

Thanks for the report!

**Comment by gregoa** [comment]
Looks good, thanks.
(I set http_proxy to something useless and the tests still work.)

**Comment by bigpresh** [comment]
Thanks for checking!
