### ISSUE TITLE
t/08_session/* break with YAML 1.30

### ISSUE THREAD

**Issue by eserte** [PerlDancer/Dancer#1208]
t/08_session/03_http_requests.t and t/08_session/05_yaml.t seem to fail if YAML 1.30 is installed, maybe because of this change: https://metacpan.org/source/TINITA/YAML-1.30/Changes#L2
(@perlpunk: FYI)

**Comment by bigpresh** [comment]
Dancer-1.3513 is on its way to CPAN currently with a fix for this.

Thanks for the report!
