### ISSUE TITLE
perldancer.org yields 502 Bad Gateway

### ISSUE THREAD

**Issue by jabowery** [PerlDancer/Dancer#1214]
To be precise:

```
502 Bad Gateway
nginx/1.14.0 (Ubuntu)
```

**Comment by bigpreshkt** [comment]
Thanks - my Nagios monitoring alarmed overnight too.  The situation appears to have resolved itself automatically around 6am this morning - (probably after log rotation and a restart?) - I'll check my logs for anything illuminating.

**Comment by bigpresh** [comment]
Thanks - my Nagios monitoring alarmed overnight too. The situation appears to have resolved itself automatically around 6am this morning - (probably after log rotation and a restart?) - I'll check my logs for anything illuminating.
