### ISSUE TITLE
Leftover file pod2htmd.tmp in v1.3520 tarball

### ISSUE THREAD

**Issue by perlpunk** [PerlDancer/Dancer#1238]
For the openSUSE update of this module I noticed the new file which I suppose is an accidental leftover: https://metacpan.org/release/BIGPRESH/Dancer-1.3520/source/pod2htmd.tmp

**Comment by cromedome** [comment]
This should be resolved with the recent release. Please feel to reopen this if you notice any other cruft in the distro.

Thanks for reporting! Sorry for the mishap.
