### ISSUE TITLE
CPAN Documentation for Dancer::Test missing a method in contents

### ISSUE THREAD

**Issue by jfharden** [PerlDancer/Dancer#984]
The CPAN page for documenting Dancer::Test (http://search.cpan.org/~yanick/Dancer-1.3120/lib/Dancer/Test.pm) has dancer_request missing from the contents list of the methods, although it does appear in the methods body.

**Comment by brad-mac** [comment]
There's no dancer_request method in 1.3120 or the latest (1.3133) version of Dancer::Test; and the nearest candidate (dancer_response) is documented. I think this issue should be closed.

**Comment by yanick** [comment]
I have to agree with brad-mac there. I'm not sure what `dancer_request` you are referring to there.

Closing for the time being. jfharden, feel free to reopen if you have more specific information on what you think is missing there.
